import type { Service, Category } from "./types";
const standard = [
  {
    id: "essential",
    name: "Essential",
    multiplier: 1,
    detail: "Everything you need to get started",
  },
  {
    id: "signature",
    name: "Signature",
    multiplier: 1.6,
    detail: "An elevated finish with extra creative options",
  },
  {
    id: "complete",
    name: "Complete",
    multiplier: 2.4,
    detail: "The full experience, with priority production",
  },
];
type Seed = [
  string,
  string,
  Category,
  number,
  number,
  number,
  number,
  number,
  Service["useCase"],
  Service["industry"],
  string,
  string?,
];
const seeds: Seed[] = [
  [
    "brand-identity",
    "Brand identity design",
    "Create",
    85000,
    150,
    120,
    205,
    7,
    "Brand launch",
    "All businesses",
    "A brand that feels unmistakably you.",
    "Bestseller",
  ],
  [
    "branded-mugs",
    "Custom ceramic mugs",
    "Gifts",
    6500,
    18,
    14,
    25,
    5,
    "Team & clients",
    "All businesses",
    "A daily dose of your brand.",
    "Popular",
  ],
  [
    "business-cards",
    "Premium business cards",
    "Prints",
    18000,
    35,
    28,
    48,
    3,
    "Everyday essentials",
    "All businesses",
    "Make your first impression a lasting one.",
    "10% off",
  ],
  [
    "social-media-kit",
    "Social media design kit",
    "Digital",
    35000,
    65,
    50,
    90,
    3,
    "Brand launch",
    "Tech & startups",
    "Show up with a scroll-stopping look.",
    "New",
  ],
  [
    "gift-box",
    "Thoughtful welcome boxes",
    "Gifts",
    28000,
    55,
    42,
    75,
    7,
    "Team & clients",
    "Tech & startups",
    "A warm welcome, beautifully packaged.",
  ],
  [
    "product-photography",
    "Product photography",
    "Studio",
    65000,
    120,
    95,
    165,
    5,
    "Brand launch",
    "Fashion & lifestyle",
    "Your products, in their best light.",
    "Bestseller",
  ],
  [
    "tote-bags",
    "Everyday branded totes",
    "Gifts",
    8000,
    22,
    17,
    30,
    5,
    "Events",
    "Fashion & lifestyle",
    "Your brand. Out and about.",
  ],
  [
    "event-backdrop",
    "Statement event backdrops",
    "Prints",
    55000,
    110,
    85,
    150,
    5,
    "Events",
    "All businesses",
    "Set the scene for something memorable.",
  ],
  [
    "logo-design",
    "Signature logo design",
    "Create",
    45000,
    90,
    70,
    125,
    5,
    "Brand launch",
    "All businesses",
    "Small mark. Big personality.",
  ],
  [
    "website-design",
    "Website design",
    "Digital",
    180000,
    450,
    350,
    620,
    14,
    "Brand launch",
    "Tech & startups",
    "Give your brand a beautiful home online.",
  ],
  [
    "packaging-design",
    "Packaging design",
    "Create",
    75000,
    140,
    110,
    190,
    7,
    "Brand launch",
    "Food & hospitality",
    "Love at first unboxing.",
  ],
  [
    "brand-film",
    "Brand story film",
    "Studio",
    250000,
    600,
    470,
    820,
    14,
    "Brand launch",
    "All businesses",
    "Turn your story into something moving.",
  ],
  [
    "thank-you-cards",
    "Personal thank-you cards",
    "Prints",
    12000,
    28,
    22,
    38,
    3,
    "Everyday essentials",
    "Fashion & lifestyle",
    "A little note goes a long way.",
  ],
  [
    "email-templates",
    "Branded email templates",
    "Digital",
    25000,
    55,
    42,
    75,
    3,
    "Everyday essentials",
    "Tech & startups",
    "An inbox introduction worth opening.",
  ],
  [
    "team-portraits",
    "Team portrait session",
    "Studio",
    90000,
    180,
    140,
    245,
    7,
    "Team & clients",
    "All businesses",
    "Meet the people behind your brand.",
  ],
  [
    "brand-strategy",
    "Brand strategy workshop",
    "Create",
    120000,
    250,
    195,
    340,
    7,
    "Brand launch",
    "Tech & startups",
    "Clarity for your next chapter.",
  ],
  [
    "branded-notebooks",
    "Custom hardcover notebooks",
    "Gifts",
    9500,
    24,
    19,
    33,
    5,
    "Team & clients",
    "All businesses",
    "A home for the next big idea.",
  ],
  [
    "restaurant-menus",
    "Beautiful restaurant menus",
    "Prints",
    22000,
    45,
    35,
    62,
    3,
    "Everyday essentials",
    "Food & hospitality",
    "Make everything look good enough to order.",
  ],
  [
    "motion-graphics",
    "Animated brand assets",
    "Digital",
    75000,
    160,
    125,
    220,
    7,
    "Events",
    "Tech & startups",
    "Give your brand a little movement.",
  ],
  [
    "creative-direction",
    "Campaign creative direction",
    "Studio",
    150000,
    320,
    250,
    440,
    10,
    "Events",
    "Fashion & lifestyle",
    "One clear vision. Every detail considered.",
  ],
];
const inclusions: Record<Category, string[]> = {
  Create: [
    "Discovery questionnaire and creative direction",
    "Two original design concepts",
    "Two rounds of refinements",
    "Final production-ready files and usage guide",
  ],
  Digital: [
    "Brand discovery and content direction",
    "Custom, on-brand digital assets",
    "Two rounds of refinements",
    "Editable source files and export formats",
  ],
  Gifts: [
    "Quality materials and branded personalisation",
    "Digital artwork proof before production",
    "Carefully checked finish",
    "Individual protective packaging",
  ],
  Studio: [
    "Creative consultation and shot planning",
    "Dedicated studio production session",
    "Professional editing and colour treatment",
    "High-resolution final assets",
  ],
  Prints: [
    "Print-ready artwork review",
    "Digital proof before printing",
    "Premium stock and colour printing",
    "Quality checks and protective packaging",
  ],
};
export const services: Service[] = seeds.map(
  (
    [
      slug,
      name,
      category,
      ng,
      us,
      uk,
      ca,
      days,
      useCase,
      industry,
      tagline,
      badge,
    ],
    index,
  ) => ({
    slug,
    name,
    category,
    tagline,
    description: `${tagline} Our ${name.toLowerCase()} service brings considered design and a careful eye for detail to your next project. Work with a dedicated creative team, approve your direction and receive something you will be proud to put your name on.`,
    prices: { ng: ng * 100, us: us * 100, uk: uk * 100, ca: ca * 100 },
    image: `/images/${slug}.svg`,
    gallery: [`/images/${slug}.svg`, `/images/${slug}-detail.svg`],
    days,
    popularity: 100 - index * 3,
    useCase,
    industry,
    badge,
    discount: slug === "business-cards" ? 10 : undefined,
    included: inclusions[category],
    options:
      category === "Prints" && slug !== "event-backdrop"
        ? [
            {
              id: "100",
              name: "100 pieces",
              multiplier: 1,
              detail: "One beautifully printed batch",
            },
            {
              id: "250",
              name: "250 pieces",
              multiplier: 2.1,
              detail: "Our most popular quantity",
            },
            {
              id: "500",
              name: "500 pieces",
              multiplier: 3.7,
              detail: "More impressions, better value",
            },
          ]
        : standard,
  }),
);
